version: '3'

services:
  app_database:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_DATABASE=social_network
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local
